# Generated by Django 3.2.9 on 2021-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
